so ~/.vim/Vimfile
so ~/.vim/config/ctrlp.vim
so ~/.vim/config/syntax.vim
so ~/.vim/config/lightline.vim
"so ~/.vim/config/vim_table_mode.vim
"so ~/.vim/config/syntax/r.vim
"so ~/.vim/config/syntax/javascript.vim
"so ~/.vim/config/ack.vim
"set mouse=a

let g:netrw_liststyle=3
let g:netrw_banner=0
set shell=bash
set background=dark
syntax on
set tabstop=2
set shiftwidth=2
set expandtab
set backspace=indent,eol,start
set number
set noswapfile
set hidden
"set nofixendofline
set viminfo='100,h
set timeoutlen=50
set shell=bash\ --rcfile\ ~/.bash_vim
colorscheme jellybeans_modified
"set iskeyword-=_

command PPjson %!python3 -m json.tool

"augroup vimrc
"  au BufReadPre * setlocal foldmethod=syntax
"  au BufWinEnter * if &fdm == 'syntax' | setlocal foldmethod=manual | endif
"augroup END

" Go Syntax Highlighting
let g:go_highlight_functions=1
let g:go_highlight_function_calls=1
let g:go_highlight_methods=1
"let g:go_highlight_variable_declarations=1
let g:go_highlight_variable_assignments=1

" use 'vim-pandoc/vim-pandoc-syntax' plugin without 'vim-pandoc'.
"augroup pandoc_syntax
"  au! BufNewFile,BufFilePre,BufRead *.md set filetype=markdown.pandoc
"augroup END
