require('config.options')
require('config.filetypes')
require('config.lazy')
require('config.lsp')
require('config.telescope')
require('config.fff')
require('config.lualine')
require('config.colorscheme')
